In [23]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# OneHotEncoder要求数据类别必须是数值的
## -- categorical_features：给定对那些列的数据进行哑编码操作，默认是对所有类数据做
## -- n_values：明确给定各个特征属性的类别数目，其实是最大值-最小值+1
### ---- enc = OneHotEncoder(categorical_features=[1,2])
### ---- enc = OneHotEncoder(n_values=[3, 3, 4])

In [30]:
enc = OneHotEncoder(drop='first')
a=np.array([[0, 0, 3], 
            [2, 1, 0], 
            [0, 2, 1], 
            [1, 0, 1],
            [1, 1, 1]])
# a = [
#     [1, 1, 2],
#     [2, 1, 1],
#     [1, 2, 1],
#     [3, 1, 2],
#     [3, 1, 2]
# ]
enc.fit(a) 
print(a)
print("编码结果",enc.categories_)
# print("原来的特征(进行哑编码的)在新的特征矩阵中的位置映射关系:")
# print(enc.feature_indices_)
# enc.transform([[1, 2, 2],
#                [2, 2, 2]]).toarray()

[[0 0 3]
 [2 1 0]
 [0 2 1]
 [1 0 1]
 [1 1 1]]
编码结果 [array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 3])]


In [29]:
print(enc.transform(a).toarray())

[[0. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0.]]


# 如果类别数据是字符串类型的，可以使用pandas的API进行哑编码转换

In [31]:
import pandas as pd

a = pd.DataFrame([
    ['a', 1, 2],
    ['b', 1, 1],
    ['a', 2, 1],
    ['c', 1, 2],
    ['c', 1, 2]
], columns=['c1', 'c2', 'c3'])
a = pd.get_dummies(a)
a

c2  c3  c1_a  c1_b  c1_c
0   1   2     1     0     0
1   1   1     0     1     0
2   2   1     1     0     0
3   1   2     0     0     1
4   1   2     0     0     1