In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer,TfidfTransformer

In [6]:
arr1 = [
    "This is spark, spark sql a every good",
    "Spark Hadoop Hbase",
    "This is sample",
    "This is anthor example anthor example",
    "spark hbase hadoop spark hive hbase hue oozie",
    "hue oozie spark"
]
arr2 = [
    "this is a sample a example",
    "this c c cd is another another sample example example",
    "spark Hbase hadoop Spark hive hbase"
]
df = arr2

In [7]:
# 相当于词袋法
count = CountVectorizer(min_df=0.1, dtype=np.float64, ngram_range=(0,1))
df1 = count.fit_transform(df)
print (df1.toarray())
print (count.get_stop_words())
print (count.get_feature_names())
print ("转换另外的文档数据")
print (count.transform(arr1).toarray())
print(df1)

[[ 0.  0.  1.  0.  0.  0.  1.  1.  0.  1.]
 [ 2.  1.  2.  0.  0.  0.  1.  1.  0.  1.]
 [ 0.  0.  0.  1.  2.  1.  0.  0.  2.  0.]]
None
['another', 'cd', 'example', 'hadoop', 'hbase', 'hive', 'is', 'sample', 'spark', 'this']
转换另外的文档数据
[[ 0.  0.  0.  0.  0.  0.  1.  0.  2.  1.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.  0.  1.]
 [ 0.  0.  2.  0.  0.  0.  1.  0.  0.  1.]
 [ 0.  0.  0.  1.  2.  1.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]]
  (0, 2)	1.0
  (0, 7)	1.0
  (0, 6)	1.0
  (0, 9)	1.0
  (1, 0)	2.0
  (1, 1)	1.0
  (1, 2)	2.0
  (1, 7)	1.0
  (1, 6)	1.0
  (1, 9)	1.0
  (2, 5)	1.0
  (2, 3)	1.0
  (2, 4)	2.0
  (2, 8)	2.0


In [8]:
# 基于TF的值(词袋法)，做一个IDF的转换
tfidf_t = TfidfTransformer()
df2 = tfidf_t.fit_transform(df1)
print (df2.toarray())
print ("转换另外的文档数据")
print (tfidf_t.transform(count.transform(arr1)).toarray())

[[ 0.          0.          0.5         0.          0.          0.          0.5
   0.5         0.          0.5       ]
 [ 0.66486672  0.33243336  0.50564828  0.          0.          0.
   0.25282414  0.25282414  0.          0.25282414]
 [ 0.          0.          0.          0.31622777  0.63245553  0.31622777
   0.          0.          0.63245553  0.        ]]
转换另外的文档数据
[[ 0.          0.          0.          0.          0.          0.
   0.3349067   0.          0.88072413  0.3349067 ]
 [ 0.          0.          0.          0.57735027  0.57735027  0.          0.
   0.          0.57735027  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.57735027  0.57735027  0.          0.57735027]
 [ 0.          0.          0.81649658  0.          0.          0.
   0.40824829  0.          0.          0.40824829]
 [ 0.          0.          0.          0.31622777  0.63245553  0.31622777
   0.          0.          0.63245553  0.        ]
 [ 0.          0.          0.       

In [9]:
## 相当TF+IDF(先做词袋法再做IDF转换)
tfidf_v = TfidfVectorizer(min_df=0, dtype=np.float64)
df3 = tfidf_v.fit_transform(df)
print (df3.toarray())
print (tfidf_v.get_feature_names())
print (tfidf_v.get_stop_words())
print ("转换另外的文档数据")
print (tfidf_v.transform(arr1).toarray())

[[ 0.          0.          0.5         0.          0.          0.          0.5
   0.5         0.          0.5       ]
 [ 0.66486672  0.33243336  0.50564828  0.          0.          0.
   0.25282414  0.25282414  0.          0.25282414]
 [ 0.          0.          0.          0.31622777  0.63245553  0.31622777
   0.          0.          0.63245553  0.        ]]
['another', 'cd', 'example', 'hadoop', 'hbase', 'hive', 'is', 'sample', 'spark', 'this']
None
转换另外的文档数据
[[ 0.          0.          0.          0.          0.          0.
   0.3349067   0.          0.88072413  0.3349067 ]
 [ 0.          0.          0.          0.57735027  0.57735027  0.          0.
   0.          0.57735027  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.57735027  0.57735027  0.          0.57735027]
 [ 0.          0.          0.81649658  0.          0.          0.
   0.40824829  0.          0.          0.40824829]
 [ 0.          0.          0.          0.31622777  0.63245553  0.31